CREATE DATABASE TelechatDevelopment;

USE TelechatDevelopment;

CREATE TABLE Users (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(255) UNIQUE NOT NULL,
	PasswordHash VARCHAR(255) NOT NULL,
	Email VARCHAR(255) UNIQUE,
	PhoneNumber VARCHAR(255) UNIQUE,
	RegisteredAt DATETIME NOT NULL
);

CREATE TABLE Rooms (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(255) UNIQUE NOT NULL,
	IsPrivate BOOLEAN NOT NULL,
	PasswordHash VARCHAR(255),
	Description TEXT,
	CreatedAt DATETIME NOT NULL
);

CREATE TABLE Messages (
	Id INT AUTO_INCREMENT PRIMARY KEY,
	Message TEXT NOT NULL,
	SentAt DATETIME NOT NULL,
	UserId INT NOT NULL,
	RoomId INT NOT NULL,
	FOREIGN KEY (UserId) REFERENCES Users(Id),
	FOREIGN KEY (RoomId) REFERENCES Rooms(Id)
);

SHOW DATABASES;
USE TelechatDevelopment;
SHOW TABLES;
