 SHOW DATABASES;
 CREATE DATABASE TelechatDevelopment;
 USE TelechatDevelopment;
 
 CREATE TABLE Messages (
	Id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	Message TEXT NOT NULL,
	Username VARCHAR(255) NOT NULL,
	SentAt DATETIME NOT NULL
 );
 
 SHOW TABLES;
 